### ISSUE TITLE
[Code Style] IterableExtension

### ISSUE THREAD

**Issue by dm430** [stevemasta34/CustomExtensions#2]
The loop in the [take](https://github.com/stevemasta34/CustomExtensions/blob/master/src/com/fox/IterableExtension.java#L64) method should be replaced with a while loop. 

Also change logic block style in [skip](https://github.com/stevemasta34/CustomExtensions/blob/master/src/com/fox/IterableExtension.java#L78)

**Comment by stephenjfox** [comment]
Why should it be done with a while loop?

**Comment by dm430** [comment]
@stevemasta34 The code fits better with a while. You are abusing the for loop.

**Comment by stephenjfox** [comment]
I would argue that the memory constraints and scope imposed by the for-construct is actually "fully utilizing" the native language
