### ISSUE TITLE
Remove String  helper for uppercase

### ISSUE THREAD

**Issue by dm430** [stevemasta34/CustomExtensions#4]
[This](https://github.com/stevemasta34/CustomExtensions/blob/master/src/com/fox/StringExtension.java#L82) functionality exists in Java natively as `toUpperCase()`

**Comment by stephenjfox** [comment]
If there was a javadoc, it would have covered this:

The mentioned function was intended to capitalize every "word" in a "sentence"; the space-delimited strings would each have their first character upper cased

**Comment by dm430** [comment]
I misread the code. I would suggest a name change then.
